services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: caio123
      MYSQL_DATABASE: payments
      MYSQL_USER: caio
      MYSQL_PASSWORD: caio123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: